# Generated by Django 5.0.6 on 2024-06-13 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('aadhaar', models.CharField(max_length=16)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='GramPanchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_name', models.CharField(max_length=100)),
                ('panchayat_address', models.CharField(max_length=100)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_assigned_panchayats', to='water_management.contractor')),
                ('panchayat_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayathead', to='water_management.person')),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_person', to='water_management.person'),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_management.contractor')),
                ('gram_panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.grampanchayat')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_reported', models.TextField()),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_quantity', models.FloatField()),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('arsenic_level', models.FloatField()),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='WaterUserCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=100)),
                ('committee_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watercommitteehead', to='water_management.person')),
                ('committee_panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committeepanchayat', to='water_management.grampanchayat')),
            ],
        ),
        migrations.CreateModel(
            name='PumpOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_operator', to='water_management.person')),
                ('water_user_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_management.waterusercommittee')),
            ],
        ),
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.FloatField(default=0)),
                ('fee_date', models.DateField()),
                ('fee_water_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feewatercommittee', to='water_management.waterusercommittee')),
            ],
        ),
    ]
