# Generated by Django 5.0.6 on 2024-06-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_rate', models.IntegerField(default=3)),
            ],
        ),
    ]
