# Generated by Django 5.0.6 on 2024-06-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0002_feerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='0000', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='person_role',
            field=models.CharField(choices=[('panchayathead', 'Panchayat Head'), ('consumer', 'Consumer')], default='consumer', max_length=20),
        ),
    ]
