# Generated by Django 5.0.6 on 2024-06-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0003_person_is_enabled_person_password_person_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gram_panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='water_management.grampanchayat'),
        ),
    ]
