# Generated by Django 5.0.6 on 2024-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0004_person_gram_panchayat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
