# Generated by Django 5.0.6 on 2024-06-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0006_alter_person_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='fee_water_committee',
        ),
        migrations.AddField(
            model_name='feecollection',
            name='concerned_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_fee', to='water_management.person'),
        ),
    ]
