# Generated by Django 5.0.6 on 2024-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0007_remove_feecollection_fee_water_committee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_role',
            field=models.CharField(choices=[('panchayathead', 'Panchayat Head'), ('consumer', 'Consumer'), ('contractor', 'Contractor')], default='consumer', max_length=20),
        ),
    ]
