# Generated by Django 5.0.6 on 2024-06-27 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0008_alter_person_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='due_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='enable_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
