# Generated by Django 5.0.6 on 2024-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0010_alter_person_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpoperator',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pumpoperator',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pumpoperator',
            name='supply_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pumpoperator',
            name='working_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
