# Generated by Django 5.0.6 on 2024-06-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0011_pumpoperator_in_time_pumpoperator_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpoperator',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='pumpoperator',
            name='out_time',
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('pump_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='water_management.pumpoperator')),
            ],
        ),
    ]
