# Generated by Django 5.0.6 on 2024-06-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_management', '0012_remove_pumpoperator_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpoperator',
            name='supply_enabled',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='supply_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
